### PR TITLE
Insert dataset

### PR DESCRIPTION
**Pull request by sartiran**
Hi,
a couple of adds to the script directory.
1- insertDataset_v2.py: rewrite/evolution (or just my own interpretation) of insertDataset.py. 
2- registerFile: just a script that register a file which is already on storage

### CODE REVIEW

**Comment by ericvaandering** [comment]
Thanks for doing this. This is taking it from a playground with the rucio API into something more real. If you can fix the indentations (and run it through pylint and/or pep8), then I can merge it and switch to using it.

**Comment by sartiran** [comment]
Yep. I will fix the indentation asap. Also I've seen a couple of bugs I should fix. BTW: at the moment the script runs requiring a site (it register replicas at a given rse). I guess it is worth to have the possibility to register all the replicas at all the site that have a given dataset/block. Wat do you think?

**Comment by ericvaandering** [comment]
That sounds like something we'll want later as we really think about a migration of existing data into Rucio. But that's next year at the earliest.

**Comment by sartiran** [comment]
Hi Eric. Did some code formatting and fixed a couple of things that were not working as expected.

**Comment by sartiran** [comment]
Done

**Pull request merged**
